apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: celery-worker
        image: 266735841992.dkr.ecr.ap-northeast-2.amazonaws.com/fastapi-kuber:latest
        command: ["celery", "-A", "src.celery_app", "worker", "--loglevel=info"]
        env:
        - name: CELERY_BROKER_URL
          value: redis://redis-service:6379/0
        - name: CELERY_RESULT_BACKEND
          value: redis://redis-service:6379/0
        - name: DATABASE_URL
          value: postgresql+psycopg2://kjune0922:dlrudalswns2@postgres-service:5432/kuber_db
