apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-kuber
  labels:
    app: fastapi-kuber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-kuber
  template:
    metadata:
      labels:
        app: fastapi-kuber
    spec:
      containers:
      - name: fastapi-kuber
        image: 266735841992.dkr.ecr.ap-northeast-2.amazonaws.com/fastapi-kuber:latest
        command: ["/bin/sh"]
        args: ["-c", "sleep 10 && uvicorn src.main:app --host 0.0.0.0 --port 8000"]
        ports:
        - containerPort: 8000
        env:
        - name: CELERY_BROKER_URL
          value: redis://redis-service:6379/0
        - name: CELERY_RESULT_BACKEND
          value: redis://redis-service:6379/0
        - name: DATABASE_URL
          value: postgresql+psycopg2://kjune0922:dlrudalswns2@postgres-service:5432/kuber_db
        envFrom:
        - secretRef:
            name: kuberzo-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi-kuber
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
